config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :members
      resources :funds
      resources :transactions
      resources :fixed_assets
      root to: "members#index"
    end
  resources :funds
  resources :retirement_portfolio
  root to: 'retirement_portfolio#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/fund.rb
class Fund < ApplicationRecord
    belongs_to :member
    has_many :transactions
end

app/controllers/admin/funds_controller.rb
module Admin
  class FundsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/funds_controller.rb
class FundsController < ApplicationController
  before_action :set_fund, only: %i[ show edit update destroy ]

  # GET /funds or /funds.json
  def index
    url = "https://api.mfapi.in/mf"
    response = Faraday.get(url)
    @all_funds = JSON.parse(response.body)
    @funds = Fund.all
  end
  
  # GET /funds/1 or /funds/1.json
  def show
  end

  # GET /funds/new
  def new
    @fund = Fund.new
  end

  # GET /funds/1/edit
  def edit
  end

  # POST /funds or /funds.json
  def create
    @fund = Fund.new(fund_params)

    respond_to do |format|
      if @fund.save
        format.html { redirect_to fund_url(@fund), notice: "Fund was successfully created." }
        format.json { render :show, status: :created, location: @fund }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @fund.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /funds/1 or /funds/1.json
  def update
    respond_to do |format|
      if @fund.update(fund_params)
        format.html { redirect_to fund_url(@fund), notice: "Fund was successfully updated." }
        format.json { render :show, status: :ok, location: @fund }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @fund.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funds/1 or /funds/1.json
  def destroy
    @fund.destroy

    respond_to do |format|
      format.html { redirect_to funds_url, notice: "Fund was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fund
      @fund = Fund.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fund_params
      params.require(:fund).permit(:fund_name, :amc_name)
    end
end

app/helpers/funds_helper.rb
module FundsHelper
end

app/views/funds/_all_funds.html.erb
<h1>Mutual Fund NAVs</h1>
<table id="example" class="table table-success table-striped">
  <thead>
    <tr>
      <th>Scheme Name</th>
      <th>Code</th>
    </tr>
  </thead>
  <tbody>
    <% @all_funds.each do |mutual_fund| %>
      <tr>
        <td><%= mutual_fund['schemeName'] %></td>
        <td><%= mutual_fund['schemeCode'] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/funds/_form.html.erb
<%= form_with(model: fund) do |form| %>
  <% if fund.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(fund.errors.count, "error") %> prohibited this fund from being saved:</h2>

      <ul>
        <% fund.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :fund_name, style: "display: block" %>
    <%= form.text_field :fund_name %>
  </div>

  <div>
    <%= form.label :amc_name, style: "display: block" %>
    <%= form.text_field :amc_name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/funds/_fund.html.erb
<div id="<%= dom_id fund %>">
  <p>
    <strong>Fund name:</strong>
    <%= fund.fund_name %>
  </p>

  <p>
    <strong>Amc name:</strong>
    <%= fund.amc_name %>
  </p>

</div>

app/views/funds/edit.html.erb
<h1>Editing fund</h1>

<%= render "form", fund: @fund %>

<br>

<div>
  <%= link_to "Show this fund", @fund %> |
  <%= link_to "Back to funds", funds_path %>
</div>

app/views/funds/index.html.erb
<p style="color: green"><%= notice %></p>
<%= render partial: 'all_funds' %>
<h1>Funds</h1>
<button type="button" class="btn btn-lg btn-danger" data-bs-toggle="popover" data-bs-title="Popover title" data-bs-content="And here's some amazing content. It's very engaging. Right?">Click to toggle popover</button>
<div id="funds">
  <% @funds.each do |fund| %>
    <%= render fund %>
    <p>
      <%= link_to "Show this fund", fund %>
    </p>
  <% end %>
</div>

<%= link_to "New fund", new_fund_path %>

app/views/funds/new.html.erb
<h1>New fund</h1>

<%= render "form", fund: @fund %>

<br>

<div>
  <%= link_to "Back to funds", funds_path %>
</div>

app/views/funds/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @fund %>

<div>
  <%= link_to "Edit this fund", edit_fund_path(@fund) %> |
  <%= link_to "Back to funds", funds_path %>

  <%= button_to "Destroy this fund", @fund, method: :delete %>
</div>